//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Hangfire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public Nullable<int> Province_id { get; set; }
        public Nullable<int> District_id { get; set; }
        public Nullable<int> Town_id { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual Town Town { get; set; }
        public virtual User User { get; set; }
    }
}
